import type { Metadata } from "next";
import "./globals.css";

import { Jura } from "next/font/google";

const jura = Jura({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-jura",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jura.variable} antialiased`}>{children}</body>
    </html>
  );
}
